### ISSUE TITLE
Release 1.2 Tasks

### ISSUE THREAD

**Issue by nethip** [adobe/brackets#10520]
### Tasks in Development
- [x] @nethip  [2 days before] Review bugs open to the current milestone
- [x] @nethip All new open bugs have been reviewed
- [x] @nethip [2 days before] Notify committers of impending merge of master into release branch
- [x] @nethip Notify ALF Team that we have reached String Freeze: `DL-Brackets-IQE` 
- [x] @prafulVaishnav Merge master to both release branches
- [x] @prksingh Kick off release build and notify team to start testing when done
- [x] @prksingh Create a Github Release using prerelease flag for release branch build for all platforms. Delete Obsolete Github Release Builds.
- [x] @prksingh Post to Brackets-Dev Forum: details about [Community Testing] (https://github.com/adobe/brackets/wiki/Brackets-Community-Testing)
- [x] @prksingh Post to Brackets-Dev Forum: request Translations in release branch
- [x] @abose Create update notifications and send to LOC `DL-Brackets-IQE`. Copy English te t to German & Spanish in case not translated.
- [x] @prksingh Create beginning of release card
- [x] @prksingh Run `grunt set-release --release=N` to update sprint number in master branches
- [x] @abose Merge update notification translations back from LOC
- [x] @abose  Send reminders to translate Brackets Update Notification strings – Spanish (@TomMalbran, @jbalsas ) 
- [x] @abose Translate Brackets Update Notification strings into German ( @marcelGerber, @pthiess, @ingorichter, )
- [x] @prksingh  Update Getting Started content and send to loc
- [x] @prksingh  README and "How to Use Brackets" wiki page reviewed and any stale information updated
- [x] @abose New 3rd party code information is added to Third Party Component Usage and NOTICE on github
- [x] LoriT Update wiki & TESSA w/ 3rd party dependencies
- [x] @ryanStewart Write Blog Post
- [x] @abose Update [Brackets Loc test procedure](https://github.com/adobe/brackets/wiki/Localization-Tests)
- [x] @nethip [Release notes] (https://github.com/adobe/brackets/wiki/Release-Notes) page on GitHub wiki added with information on features added, bugs fixed in the sprint, and major known issues. All "for release note" bugs added.
- [x] @prafulVaishnav  Regenerate and post API documentation to brackets.io

### Tasks in Testing
- [x] @prafulVaishnav Verify that automated Unit Test Cascade after build succeeded (test jobs succeeded) and then trigger signing process for release candidate.
- [x] @prafulVaishnav All bugs for all stories completed in the release are closed (or given an exception after review)
- [x] @prafulVaishnav All unit, extension and client & server smoke tests for the entire product pass – Win
- [x] @prafulVaishnav All unit, extension and client & server smoke tests for the entire product pass – Mac
- [x] @abose All unit, extension and client & server smoke tests for the entire product pass – Linux 32
- [x] @abose All unit, extension and client & server smoke tests for the entire product pass – Linux 64
- [x] @nethip Test Win installer / verify digital signature on .msi, .exe, .dlls (both vanilla and bundle)
- [x] @nethip Windows: Scenario testing
- [x] @prksingh Test Mac installer / verify digital signature on .app & binaries (both vanilla and bundle)
- [x] @prksingh Mac: Scenario testing
- [x] @nethip Test Linux 32 installer + scenario testing
- [x] @nethip Test Linux 64 installer + scenario testing

**Comment by peterflynn** [comment]
Closing since all the tasks are now done (blog post was the last one)
