### ISSUE TITLE
Release 1.2 Deployment Tasks

### ISSUE THREAD

**Issue by nethip** [adobe/brackets#10521]
### Tasks to deploy a release publicly
- [x] Tag the build (brackets, brackets-shell) using `release-1.0` format (Creating 'Release' in brackets tags the build, so only need to do this in brackets-shell?)
- [x] Announcement to the brackets-dev group for this release and work in the new cycle
- [x] Merge localizations/other release changes back into master
- [x] Merge localizations/other release changes to brackets-shell master
- [x] Create a bundle with the Extract extension
- [x] Create a new release on github.com/adobe/brackets/releases 
- [x] Rename and post all 4 platform Builds to github.com/adobe/brackets/releases page
- [x] Publish the release on github.com/adobe/brackets/releases
- [x] Update build number & date in brackets-updates repo _AND_ push Brackets update notifications to brackets.io (*for ALL 5 locales*)
- [x] Verify posted builds Mac
- [x] Verify posted builds Windows
- [x] Verify posted builds Linux 64
- [x] Verify posted builds Linux 32
- [x] Post Blog post
- [x] Double-check brackets.io home page to make sure button and new features list look right
- [x] Verify that update notifications work from an older build
- [x] Announce release in post to [Facebook](https://www.facebook.com/codebrackets) and [Google+](https://plus.google.com/115365194873502050036/posts), twitter
- [x] @ingorichter Post announcement in brackets-announce
- [ ] @pthiess Gather cycle times from "Ship It!” column
- [ ] Schedule Review Meeting
