### ISSUE TITLE
Release 1.4 Tasks

### ISSUE THREAD

**Issue by abose** [adobe/brackets#11256]
### Tasks in Development
- [x] [2 days before] Review bugs open to the current milestone
- [x] All new open bugs have been reviewed
- [x] [2 days before] Notify committers of impending merge of master into release branch @prafulVaishnav 
- [x] Notify ALF Team that we have reached String Freeze: `DL-Brackets-IQE` @prafulVaishnav
- [x] Merge master to both release branches @prafulVaishnav
- [x] Release 1.4 ONLY merge brackets-shell/pull/509 into Linux release branch.
- [x] Kick off release build and notify team to start testing when done @nethip 
- [x] Create a Github Release using prerelease flag for release branch build for all platforms. Delete Obsolete Github Release Builds. @prafulVaishnav
- [x] Post to Brackets-Dev Forum: details about [Community Testing] @rroshan1 (https://github.com/adobe/brackets/wiki/Brackets-Community-Testing)
- [x] Post to Brackets-Dev Forum: request Translations in release branch @rroshan1 
- [x] Create update notifications and send to LOC `DL-Brackets-IQE`. Copy English translations to German & Spanish in case not translated. @abose 
- [x] Create beginning of release card @nethip 
- [x] Run `grunt set-release --release=N` to update sprint number in master branches @prafulVaishnav
- [x] Merge update notification translations back from LOC @rroshan1 
- [x] Send reminders to translate Brackets Update Notification strings – Spanish (@TomMalbran, @jbalsas ) @prafulVaishnav
- [x] Translate Brackets Update Notification strings into German ( @marcelGerber, @pthiess, @ingorichter, ) @prafulVaishnav
- [x] Update Getting Started content and send to loc @rroshan1 
- [x] README and "How to Use Brackets" wiki page reviewed and any stale information updated @rroshan1 
- [x] New 3rd party code information is added to Third Party Component Usage and NOTICE on github
- [x] Sarthak Update wiki & TESSA w/ 3rd party dependencies
- [x] Write Blog Post @nethip 
- [x] Update [Brackets Loc test procedure](https://github.com/adobe/brackets/wiki/Localization-Tests) @abose 
- [x] [Release notes] (https://github.com/adobe/brackets/wiki/Release-Notes) page on GitHub wiki added with information on features added, bugs fixed in the sprint, and major known issues. All "for release note" bugs added. @nethip 
- [x] Regenerate and post API documentation to brackets.io @prafulVaishnav

### Tasks in Testing
- [x] Verify that automated Unit Test Cascade after build succeeded (test jobs succeeded) and then trigger signing process for release candidate.
- [x] All bugs for all stories completed in the release are closed (or given an exception after review)
- [x] All unit, extension and client & server smoke tests for the entire product pass – Win
- [x] All unit, extension and client & server smoke tests for the entire product pass – Mac
- [x] All unit, extension and client & server smoke tests for the entire product pass – Linux 32
- [x] All unit, extension and client & server smoke tests for the entire product pass – Linux 64
- [x] Test Win installer / verify digital signature on .msi, .exe, .dlls (both vanilla and bundle)
- [x] Windows: Scenario testing
- [x] Test Mac installer / verify digital signature on .app & binaries (both vanilla and bundle)
- [x] Mac: Scenario testing
- [x] Test Linux 32 installer + scenario testing
- [x] Test Linux 64 installer + scenario testing
