### ISSUE TITLE
Release 1.5 Tasks

### ISSUE THREAD

**Issue by nethip** [adobe/brackets#11757]
### Tasks in Development
- [x] [2 days before] Review bugs open to the current milestone
- [x] All new open bugs have been reviewed
- [x] [2 days before] Notify committers of impending merge of master into release branch 
- [x] Notify ALF Team that we have reached String Freeze: `DL-Brackets-IQE`
- [x] Merge master to both release branches
- [x] Kick off release build and notify team to start testing when done 
- [x] Create a Github Release using prerelease flag for release branch build for all platforms. Delete Obsolete Github Release Builds.
- [x] Post to Brackets-Dev Forum: details about [Community Testing] (https://github.com/adobe/brackets/wiki/Brackets-Community-Testing)
- [x] Post to Brackets-Dev Forum: request Translations in release branch 
- [x] Create update notifications and send to LOC `DL-Brackets-IQE`. Copy English translations to German & Spanish in case not translated. 
- [x] Create beginning of release card 
- [x] Run `grunt set-release --release=N` to update sprint number in master branches
- [x] Merge update notification translations back from LOC 
- [x] Send reminders to translate Brackets Update Notification strings – Spanish (@TomMalbran, @jbalsas )
- [x] Translate Brackets Update Notification strings into German ( @marcelGerber, @pthiess, @ingorichter, )
- [x] Update Getting Started content and send to loc 
- [x] README and How to Use Brackets" wiki page reviewed and any stale information updated 
- [x] New 3rd party code information is added to Third Party Component Usage and NOTICE on github
- [ ] Sarthak Update wiki & TESSA w/ 3rd party dependencies
- [ ] Write Blog Post 
- [x] Update [Brackets Loc test procedure](https://github.com/adobe/brackets/wiki/Localization-Tests) 
- [x] [Release notes] (https://github.com/adobe/brackets/wiki/Release-Notes) page on GitHub wiki added with information on features added, bugs fixed in the sprint, and major known issues. All "for release note" bugs added. 
- [x] Regenerate and post API documentation to brackets.io @swmitra 

### Tasks in Testing
- [x] Verify that automated Unit Test Cascade after build succeeded (test jobs succeeded) and then trigger signing process for release candidate.
- [x] All bugs for all stories completed in the release are closed (or given an exception after review)
- [x] All unit, extension and client & server smoke tests for the entire product pass – Win
- [x] All unit, extension and client & server smoke tests for the entire product pass – Mac
- [x] All unit, extension and client & server smoke tests for the entire product pass – Linux 32
- [x] All unit, extension and client & server smoke tests for the entire product pass – Linux 64
- [x] Test Win installer / verify digital signature on .msi, .exe, .dlls (both vanilla and bundle)
- [x] Windows: Scenario testing
- [x] Test Mac installer / verify digital signature on .app & binaries (both vanilla and bundle)
- [x] Mac: Scenario testing
- [x] Test Linux 32 installer + scenario testing
- [x] Test Linux 64 installer + scenario testing

**Comment by abose** [comment]
1.5 released. closing.
