### ISSUE TITLE
Release 1.7 activities

### ISSUE THREAD

**Issue by nethip** [adobe/brackets#12387]
### Tasks in Development
- [x] [2 days before] Review bugs open to the current milestone @swmitra 
- [x] All new open bugs have been reviewed @swmitra 
- [x] [2 days before] Notify committers of impending merge of master into release branch @nethip
- [x] Notify ALF Team that we have reached String Freeze: `DL-Brackets-IQE` @nethip
- [x] Merge master to both release branches @nethip
- [x] Give a head's up to the LOC team for LOC testing @nethip 
- [x] Kick off release build and notify team to start testing when done @nethip 
- [x] Create a Github Release using prerelease flag for release branch build for all platforms. Delete Obsolete Github Release Builds.@nethip
- [x] Post to Brackets-Dev Forum: details about [Community Testing] @swmitra (https://github.com/adobe/brackets/wiki/Brackets-Community-Testing)
- [x] Post to Brackets-Dev Forum: request Translations in release branch @swmitra 
- [x] Create update notifications and send to LOC `DL-Brackets-IQE`. Copy English translations to German & Spanish in case not translated. 
- [x] Create beginning of release card 
- [x] Run `grunt set-release --release=N` to update sprint number in master branches @swmitra 
- [x] Merge update notification translations back from LOC @nethip
- [x] Send reminders to translate Brackets Update Notification strings – Spanish (@TomMalbran, @jbalsas ) @nethip
- [x] Translate Brackets Update Notification strings into German ( @marcelGerber, @pthiess, @ingorichter, ) @nethip
- [x] Update Getting Started content and send to loc @swmitra 
- [x] README and How to Use Brackets" wiki page reviewed and any stale information updated @swmitra 
- [x] New 3rd party code information is added to Third Party Component Usage and NOTICE on github [Suhas]
- [x] Suhas Update wiki & TESSA w/ 3rd party dependencies 
- [ ] Write Blog Post [@ryanStewart]
- [x] Update [Brackets Loc test procedure](https://github.com/adobe/brackets/wiki/Localization-Tests) @swmitra 
- [x] [Release notes] (https://github.com/adobe/brackets/wiki/Release-Notes) page on GitHub wiki @swmitra added with information on features added, bugs fixed in the sprint, and major known issues. All "for release note" bugs added. 
- [x] Regenerate and post API documentation to brackets.io @swmitra 

### Tasks in Testing
- [x] Verify that automated Unit Test Cascade after build succeeded (test jobs succeeded) and then trigger signing process for release candidate. @nethip
- [x] All bugs for all stories completed in the release are closed (or given an exception after review) @nethip
- [x] All unit, extension and client & server smoke tests for the entire product pass – Win @nethip
- [x] All unit, extension and client & server smoke tests for the entire product pass – Mac 
- [x] All unit, extension and client & server smoke tests for the entire product pass – Linux 32 @swmitra 
- [x] All unit, extension and client & server smoke tests for the entire product pass – Linux 64 @swmitra 
- [x] Test Win installer / verify digital signature on .msi, .exe, .dlls (both vanilla and bundle) @nethip
- [x] Windows: Scenario testing
- [x] Test Mac installer / verify digital signature on .app & binaries (both vanilla and bundle) 
- [x] Mac: Scenario testing
- [x] Test Linux 32 installer + scenario testing @swmitra 
- [x] Test Linux 64 installer + scenario testing @swmitra
