### ISSUE TITLE
Release 1.8 Tasks

### ISSUE THREAD

**Issue by swmitra** [adobe/brackets#12840]
### Tasks in Development
- [X] [2 days before] Review bugs open to the current milestone @swmitra
- [X] All new open bugs have been reviewed @swmitra
- [X] [2 days before] Notify committers of impending merge of master into release branch @nethip/@swmitra
- [X] Notify ALF Team that we have reached String Freeze: `DL-Brackets-IQE` @saurabh95
- [X] Merge master to both release branches @swmitra
- [X] Give a head's up to the LOC team for LOC testing @swmitra
- [X] Kick off release build and notify team to start testing when done @swmitra
- [X] Create a Github Release using prerelease flag for release branch build for all platforms. Delete Obsolete Github Release Builds. @swmitra
- [X] Post to Brackets-Dev Forum: details about [Community Testing](https://github.com/adobe/brackets/wiki/Brackets-Community-Testing) @swmitra
- [X] Post to Brackets-Dev Forum: request Translations in release branch @swmitra
- [X] Create update notifications and send to LOC `DL-Brackets-IQE`. Copy English translations to German & Spanish in case not translated. @swmitra
- [ ] Create beginning of release card @rbharti
- [X] Run `grunt set-release --release=N` to update sprint number in master branches(brackets and brackets-shell) @shubhsnov
- [X] Merge update notification translations back from LOC @swmitra
- [X] Send reminders to translate Brackets Update Notification strings – Spanish  @swmitra
- [X] Translate Brackets Update Notification strings into German
- [X] Update Getting Started content and send to loc
- [X] README and How to Use Brackets" wiki page reviewed and any stale information updated
- [X] New 3rd party code information is added to Third Party Component Usage and NOTICE on github [Suhas]
- [X] Suhas Update wiki & TESSA w/ 3rd party dependencies 
- [X] Write Blog Post [@rbharti]
- [X] Update [Brackets Loc test procedure](https://github.com/adobe/brackets/wiki/Localization-Tests)
- [X] [Release notes](https://github.com/adobe/brackets/wiki/Release-Notes) page on GitHub wiki added with information on features added, bugs fixed in the sprint, and major known issues. All "for release note" bugs added. @swmitra
- [X] Regenerate and post API documentation to brackets.io @swmitra
### Tasks in Testing
- [X] Verify that automated Unit Test Cascade after build succeeded (test jobs succeeded) and then trigger signing process for release candidate.
- [X] All bugs for all stories completed in the release are closed (or given an exception after review)
- [X] All unit, extension and client & server smoke tests for the entire product pass – Win
- [X] All unit, extension and client & server smoke tests for the entire product pass – Mac 
- [X] All unit, extension and client & server smoke tests for the entire product pass – Linux 32 
- [X] All unit, extension and client & server smoke tests for the entire product pass – Linux 64 
- [X] Test Win installer / verify digital signature on .msi, .exe, .dlls
- [X] Windows: Scenario testing
- [X] Test Mac installer / verify digital signature on .app & binaries (both vanilla and bundle) 
- [X] Mac: Scenario testing
- [X] Test Linux 32 installer + scenario testing
- [X] Test Linux 64 installer + scenario testing
