### ISSUE TITLE
Release 1.10 Tasks

### ISSUE THREAD

**Issue by swmitra** [adobe/brackets#13486]
### Tasks in Development
- [x] Review Health Data Stats. @saurabh95
- [x] [2 days before] Review bugs open to the current milestone
- [x] All new open bugs have been reviewed
- [x] [2 days before] Notify committers of impending merge of master into release branch
- [x] Notify ALF Team that we have reached String Freeze: `DL-Brackets-IQE`
- [x] Merge master to both release branches
- [x] Give a head's up to the LOC team for LOC testing
- [x] Kick off release build and notify team to start testing when done
- [x] Create a Github Release using prerelease flag for release branch build for all platforms. Delete Obsolete Github Release Builds.
- [x] Post to Brackets-Dev Forum: details about [Community Testing](https://github.com/adobe/brackets/wiki/Brackets-Community-Testing)
- [x] Post to Brackets-Dev Forum: request Translations in release branch
- [x] Create update notifications and send to LOC `DL-Brackets-IQE`. Copy English translations to German & Spanish in case not translated.
- [x] Create beginning of release card
- [x] Run `grunt set-release --release=N` to update sprint number in master branches(brackets and brackets-shell)
- [x] Merge update notification translations back from LOC @swmitra 
- [x] Send reminders to translate Brackets Update Notification strings – Spanish @swmitra 
- [x] Translate Brackets Update Notification strings into German @swmitra 
- [x] Update Getting Started content and send to loc @saurabh95
- [x] README and How to Use Brackets" wiki page reviewed and any stale information updated @saurabh95
- [x] New 3rd party code information is added to Third Party Component Usage and NOTICE on github
- [x] Suhas Update wiki & TESSA w/ 3rd party dependencies @suhas
- [x] Write Blog Post @rajnish @swmitra 
- [x] Update [Brackets Loc test procedure](https://github.com/adobe/brackets/wiki/Localization-Tests) @VibhaMalhotra 
- [x] [Release notes](https://github.com/adobe/brackets/wiki/Release-Notes) page on GitHub wiki added with information on features added, bugs fixed in the sprint, and major known issues. All "for release note" bugs added. @saurabh95
- [x] Regenerate and post API documentation to brackets.io @swmitra 
### Tasks in Testing
- [x] Verify that automated Unit Test Cascade after build succeeded (test jobs succeeded) and then trigger signing process for release candidate. @nethip 
- [x] All bugs for all stories completed in the release are closed (or given an exception after review)
- [x] All unit, extension and client & server smoke tests for the entire product pass – Win @saurabh95
- [x] All unit, extension and client & server smoke tests for the entire product pass – Mac @nethip 
- [x] All unit, extension and client & server smoke tests for the entire product pass – Linux 32 @saurabh95 
- [x] All unit, extension and client & server smoke tests for the entire product pass – Linux 64 @nethip 
- [x] Test Win installer / verify digital signature on .msi, .exe, .dlls @saurabh95
- [x] Windows: Scenario testing @saurabh95
- [x] Test Mac installer / verify digital signature on .app & binaries (both vanilla and bundle) @saurabh95
- [x] Mac: Scenario testing @saurabh95
- [x] Test Linux 32 installer + scenario testing @saurabh95
- [x] Test Linux 64 installer + scenario testing @nethip
