### ISSUE TITLE
Brackets 1.12 hot fix release activities

### ISSUE THREAD

**Issue by nethip** [adobe/brackets#14093]
### Tasks in Development
- [x] Test the build on a clean VMImage of Win7 
- [x] Test the build on a clean VMImage of Win8.1 
- [x] Test the build on a clean VMImage of Win10 
- [x] Test the build on a clean Mac machine for 10.13 
- [x] Test the build on a clean Mac machine for 10.12 
- [x] Test the build on a clean Mac machine for 10.11  
- [x] Create a Github Release using prerelease flag for release branch build for all platforms. Delete Obsolete Github Release Builds.
- [x] Write Blog Post

### Tasks in Testing
- [ ] Verify that automated Unit Test Cascade after build succeeded (test jobs succeeded) and then trigger signing process for release candidate. @navch @nethip @swmitra`
- [x] All unit, extension and client & server smoke tests for the entire product pass – Win @ayushrathi15 
- [x] All unit, extension and client & server smoke tests for the entire product pass – Mac @ayushrathi15 
- [x] All unit, extension and client & server smoke tests for the entire product pass – Linux 32 @ayushrathi15 
- [x] All unit, extension and client & server smoke tests for the entire product pass – Linux 64 @ayushrathi15 
- [x] Test Win installer / verify digital signature on .msi, .exe, .dlls @ayushrathi15 
- [x] Windows: Scenario testing @ayushrathi15 
- [x] Test Mac installer / verify digital signature on .app & binaries (both vanilla and bundle) @ayushrathi15 
- [x] Mac: Scenario testing @ayushrathi15 
- [x] Test Linux 32 installer + scenario testing @ayushrathi15 
- [x] Test Linux 64 installer + scenario testing @ayushrathi15 

### Deployment
- [x] Announcement to the brackets-dev group for this release and work in the new cycle @nethip
- [x] Update Brackets 1.12 release with updated installers @ github.com/adobe/brackets/releases @nethip
- [x] Publish the release on github.com/adobe/brackets/releases @nethip / @swmitra
- [x] Update build number & date in brackets-updates repo _AND_ push Brackets update notifications to brackets.io (_for ALL 5 locales_) @swmitra
- [x] Verify posted builds Mac @swmitra
- [x] Verify posted builds Windows @navch
- [x] Verify posted builds Linux 64 @nethip
- [x] Verify posted builds Linux 32 @ayushrathi15
- [x] Post Blog post @rajnish
- [x] Double-check brackets.io home page to make sure button and new features list look right
- [x] Verify that update notifications work from an older build @nethip
- [x] Announce release in post to [Facebook](https://www.facebook.com/codebrackets) and [Google+](https://plus.google.com/115365194873502050036/posts), twitter
