### ISSUE TITLE
Release 1.13 tasks

### ISSUE THREAD

**Issue by vickramdhawal** [adobe/brackets#14376]
### Tasks in Development
- [ ] Test the build on a clean VMImage of Win7 
- [ ] Test the build on a clean VMImage of Win8.1 
- [ ] Test the build on a clean VMImage of Win10 
- [ ] Test the build on a clean Mac machine for 10.13 
- [ ] Test the build on a clean Mac machine for 10.12 
- [ ] Test the build on a clean Mac machine for 10.11  
- [ ] Review Health Data Stats.
- [ ] [2 days before] Review bugs open to the current milestone
- [ ] All new open bugs have been reviewed
- [ ] [2 days before] Notify committers of impending merge of master into release branch
- [ ] Notify ALF Team that we have reached String Freeze: `DL-Brackets-IQE`
- [ ] Merge master to both release branches
- [ ] Give a head's up to the LOC team for LOC testing
- [ ] Kick off release build and notify team to start testing when done @swmitra
- [ ] Create a Github Release using prerelease flag for release branch build for all platforms. Delete Obsolete Github Release Builds.
- [ ] Post to Brackets-Dev Forum: details about [Community Testing](https://github.com/adobe/brackets/wiki/Brackets-Community-Testing)
- [ ] Post to Brackets-Dev Forum: request Translations in release branch
- [ ] Create update notifications and send to LOC `DL-Brackets-IQE`. Copy English translations to German & Spanish in case not translated.
- [ ] Create beginning of release card
- [ ] Run `grunt set-release --release=N` to update sprint number in master branches(brackets and brackets-shell)
- [ ] Merge update notification translations back from LOC 
- [ ] Send reminders to translate Brackets Update Notification strings – Spanish
- [ ] Translate Brackets Update Notification strings into German  
- [ ] Update Getting Started content and send to loc
- [ ] README and How to Use Brackets" wiki page reviewed and any stale information updated
- [ ] New 3rd party code information is added to Third Party Component Usage and NOTICE on github
- [ ] Suhas Update wiki & TESSA w/ 3rd party dependencies @suhas
- [ ] Write Blog Post
- [ ] Update [Brackets Loc test procedure](https://github.com/adobe/brackets/wiki/Localization-Tests) @VibhaMalhotra 
- [ ] [Release notes](https://github.com/adobe/brackets/wiki/Release-Notes) page on GitHub wiki added with information on features added, bugs fixed in the sprint, and major known issues. All "for release note" bugs added. @boopeshmahendran
- [ ] Regenerate and post API documentation to brackets.io **(Use Mac OS for generating API docs)**
### Tasks in Testing
- [ ] Verify that automated Unit Test Cascade after build succeeded (test jobs succeeded) and then trigger signing process for release candidate.
- [ ] All bugs for all stories completed in the release are closed (or given an exception after review)
- [ ] All unit, extension and client & server smoke tests for the entire product pass – Win @ayushrathi15 
- [ ] All unit, extension and client & server smoke tests for the entire product pass – Mac @ayushrathi15 
- [ ] All unit, extension and client & server smoke tests for the entire product pass – Linux 32 @ayushrathi15 
- [ ] All unit, extension and client & server smoke tests for the entire product pass – Linux 64 @ayushrathi15 
- [ ] Test Win installer / verify digital signature on .msi, .exe, .dlls @ayushrathi15 
- [ ] Windows: Scenario testing @ayushrathi15 
- [ ] Test Mac installer / verify digital signature on .app & binaries (both vanilla and bundle) @ayushrathi15 
- [ ] Mac: Scenario testing @ayushrathi15 
- [ ] Test Linux 32 installer + scenario testing @ayushrathi15 
- [ ] Test Linux 64 installer + scenario testing @ayushrathi15
