### ISSUE TITLE
Release 1.13.1 (Windows only) Deployment Tasks

### ISSUE THREAD

**Issue by nethip** [adobe/brackets#14602]
### Tasks to deploy a release publicly

- [ ] Reupload Windows 1.13 build with 1.13.1
- [ ] Verify posted builds Windows @ayushrathi15 @nethip 
- [ ] Post Blog post @rajnishb
- [ ] Double-check brackets.io home page to make sure button and new features list look right @ayushrathi15 @RuchiAgrawalAdobe @malik-Surbhi  
- [ ] Verify that update notifications work from an older build @ayushrathi15 @malik-Surbhi
- [ ] Announce release in post to [Facebook](https://www.facebook.com/codebrackets) and [Google+](https://plus.google.com/115365194873502050036/posts), twitter @suhas
