### ISSUE TITLE
Release card for (Windows only) 1.13.1 Release

### ISSUE THREAD

**Issue by nethip** [adobe/brackets#14601]
### Tasks in Development
- [ ] [2 days before] Review bugs open to the current milestone @nethip @yprasad1 
- [ ] All new open bugs have been reviewed @nethip @yprasad1 
- [ ] Merge master to the release branch - both _brackets_ & _brackets-shell_
- [ ] Give a head's up to the Core & LOC teams for release testing @yprasad1 
- [ ] Kick off release build and notify team to start endgame testing when done @swmitra
- [ ] Test the build on a clean VMImage of Win7 @ayushrathi15 @RuchiAgrawalAdobe 
- [ ] Test the build on a clean VMImage of Win8.1 @ayushrathi15 @RuchiAgrawalAdobe 
- [ ] Test the build on a clean VMImage of Win10 @ayushrathi15 @RuchiAgrawalAdobe 
- [ ] Create update notifications and send to LOC `DL-Brackets-IQE`. Copy English translations to German & Spanish in case not translated. --> Rajnish
- [ ] Add new public release info to prerelease update notification @nethip 
- [ ] Merge update notification translations back from LOC @nethip 
- [ ] Translate Brackets Update Notification strings
- [ ] Write Blog Post @rajnish
- [ ] Update [Brackets Loc test procedure](https://github.com/adobe/brackets/wiki/Localization-Tests) @RuchiAgrawalAdobe 
- [ ] [Release notes](https://github.com/adobe/brackets/wiki/Release-Notes) page on GitHub wiki added with information on features added, bugs fixed in the sprint, and major known issues. All "for release note" bugs added. @sobisht 
### Tasks in Testing
- [ ] Verify that automated Unit Test Cascade after build succeeded (test jobs succeeded) and then trigger signing process for release candidate. @sobisht 
- [ ] All unit, extension and client & server smoke tests for the entire product pass – Win @ayushrathi15, @sobisht
- [ ] Test Win installer / verify digital signature on .msi, .exe, .dlls @ayushrathi15 
- [ ] Windows: Scenario testing @ayushrathi15
