### ISSUE TITLE
Release 1.14 Tasks

### ISSUE THREAD

**Issue by shubhsnov** [adobe/brackets#14725]
### Tasks in Development
- [x] Review Health Data Stats. 
- [x] Review Adobe Analytics Data on server.   
- [x] [2 days before] Review bugs open to the current milestone   
- [x] All new open bugs have been reviewed   
- [x] [2 days before] Notify committers of impending merge of master into release branch  
- [x] Notify ALF Team that we have reached String Freeze: `DL-Brackets-IQE`  
- [x] Merge master to the release branch - both _brackets_ & _brackets-shell_
- [x] Give a head's up to the Core & LOC teams for release testing  
- [x] Kick off release build and notify team to start endgame testing when done 
- [x] Test the build on a clean VMImage of Win7   
- [x] Test the build on a clean VMImage of Win8.1   
- [x] Test the build on a clean VMImage of Win10   
- [x] Test the build on a clean Mac machine for 10.13   
- [x] Test the build on a clean Mac machine for 10.12   
- [x] Test the build on a clean Mac machine for 10.11   
- [x] Test the build on a clean Ubuntu 64 Bit machine   
- [x] Test the build on a clean Ubuntu 32 Bit machine   
- [x] Test the build on a clean Debian 64 Bit machine   
- [x] Test the build on a clean Debian 32 Bit machine   
- [ ] Create a Github Release using prerelease flag for release branch build for all platforms. Delete Obsolete Github Release Builds.
- [x] Post to Brackets-Dev Forum: details about [Community Testing](https://github.com/adobe/brackets/wiki/Brackets-Community-Testing)  
- [x] Post to Brackets-Dev Forum: request Translations in release branch  
- [x] Create update notifications and send to LOC `DL-Brackets-IQE`. Copy English translations to German & Spanish in case not translated. 
#Setup
- [ ] Add new public release info to prerelease update notification  
- [ ] Create beginning of next release card  
- [x] Run `grunt set-release --release=N` to update sprint number in master branches(brackets and brackets-shell)  
- [x] Merge update notification translations back from LOC  
- [x] Send reminders to translate Brackets Update Notification strings – Spanish  
- [x] Translate Brackets Update Notification strings into German    
- [ ] Update Getting Started content and send to loc  - applicable for 1.14 ?
- [ ] README and How to Use Brackets" wiki page reviewed and any stale information updated    
- [ ] New 3rd party code information is added to Third Party Component Usage and NOTICE on github 
- [ ] Update wiki & TESSA w/ 3rd party dependencies 
- [ ] Write Blog Post 
- [ ] Update [Brackets Loc test procedure](https://github.com/adobe/brackets/wiki/Localization-Tests)  
- [x] [Release notes](https://github.com/adobe/brackets/wiki/Release-Notes) page on GitHub wiki added with information on features added, bugs fixed in the sprint, and major known issues. All "for release note" bugs added.  
- [x] [Regenerate ](https://github.com/adobe/brackets/wiki/Generating-Brackets-API-Docs)and post API documentation to brackets.io **(Use Mac OS for generating API docs)**  
### Tasks in Testing
- [x] Verify that automated Unit Test Cascade after build succeeded (test jobs succeeded) and then trigger signing process for release candidate.  
- [x] All bugs for all stories completed in the release are closed (or given an exception after review)     
- [x] All unit, extension and client & server smoke tests for the entire product pass – Win , 
- [x] All unit, extension and client & server smoke tests for the entire product pass – Mac , 
- [x] All unit, extension and client & server smoke tests for the entire product pass – Linux 32 , 
- [x] All unit, extension and client & server smoke tests for the entire product pass – Linux 64 , 
- [x] Test Win installer / verify digital signature on .msi, .exe, .dlls  
- [x] Windows: Scenario testing  
- [x] Test Mac installer / verify digital signature on .app & binaries (both vanilla and bundle)  
- [x] Mac: Scenario testing  
- [x] Test Linux 32 installer + scenario testing  
- [x] Test Linux 64 installer + scenario testing
