### ISSUE TITLE
Release 1.14.1 Tasks

### ISSUE THREAD

**Issue by yprasad1** [adobe/brackets#14964]
### Tasks in Development
- [ ] Review Health Data Stats @jha-g 
- [ ] Review Adobe Analytics Data on server.  @jha-g
- [ ] [2 days before] Review bugs open to the current milestone @narayani28 @yprasad1   
- [ ] All new open bugs have been reviewed   @narayani28 @yprasad1 
- [ ] [2 days before] Notify committers of impending merge of master into release branch @jha-g 
- [ ] Notify ALF Team that we have reached String Freeze: `DL-Brackets-IQE`   @narayani28 
- [ ] Merge master to the release branch - both _brackets_ & _brackets-shell @jha-g 
- [ ] Give a head's up to the Core & LOC teams for release testing  @jha-g 
- [ ] Kick off release build and notify team to start endgame testing when done @jha-g 
- [ ] Test the build on a clean VMImage of Win7   @malik-Surbhi 
- [ ] Test the build on a clean VMImage of Win8.1   @malik-Surbhi 
- [ ] Test the build on a clean VMImage of Win10   @Nainabhandari8
- [ ] Test the build on a clean Mac machine for 10.15   @Nainabhandari8
- [ ] Test the build on a clean Mac machine for 10.14   @malik-Surbhi 
- [ ] Test the build on a clean Mac machine for 10.13   @malik-Surbhi 
- [ ] Test the build on a clean Ubuntu 64 Bit machine   @Nainabhandari8
- [ ] Test the build on a clean Ubuntu 32 Bit machine   @malik-Surbhi 
- [ ] Test the build on a clean Debian 64 Bit machine   @Nainabhandari8
- [ ] Test the build on a clean Debian 32 Bit machine   @malik-Surbhi 
- [ ] Create a Github Release using release flag for release branch build for all platforms. Delete Obsolete Github Release Builds. @jha-g 
- [ ] Post to Brackets-Dev Forum: details about [Community Testing](https://github.com/adobe/brackets/wiki/Brackets-Community-Testing)  @swmitra @jha-g 
- [ ] Post to Brackets-Dev Forum: request Translations in release branch  @swmitra  @jha-g
- [ ] Create update notifications and send to LOC `DL-Brackets-IQE`. Copy English translations to German & Spanish in case not translated. @jha-g 
- [ ] Add new public release info to release update notification  @jha-g 
- [x] Create beginning of next release card. 
- [ ] Run `grunt set-release --release=N` to update sprint number in master branches(brackets and brackets-shell)  @jha-g
- [ ] New 3rd party code information is added to Third Party Component Usage and NOTICE on github @jha-g 
- [ ] Merge update notification translations back from LOC  @jha-g 
- [ ] Send reminders to translate Brackets Update Notification strings – Spanish @jha-g 
- [ ] Translate Brackets Update Notification strings into German    @malik-Surbhi @jha-g 
- [ ] Update Getting Started content and send to loc  @jha-g
- [ ] README and How to Use Brackets" wiki page reviewed and any stale information updated    @jha-g
- [ ] Update wiki & TESSA w/ 3rd party dependencies --> Vikram
- [ ] Write Blog Post --> Vikram
- [ ] Update [Brackets Loc test procedure](https://github.com/adobe/brackets/wiki/Localization-Tests)  @malik-Surbhi 
- [ ] [Release notes](https://github.com/adobe/brackets/wiki/Release-Notes) page on GitHub wiki added with information on features added, bugs fixed in the sprint, and major known issues. All "for release note" bugs added.  @jha-g
- [ ] [Regenerate ](https://github.com/adobe/brackets/wiki/Generating-Brackets-API-Docs)and post API documentation to brackets.io **(Use Mac OS for generating API docs)**  @jha-g 
### Tasks in Testing
- [ ] Verify that automated Unit Test Cascade after build succeeded (test jobs succeeded) and then trigger signing process for release candidate.  @jha-g
- [ ] All bugs for all stories completed in the release are closed (or given an exception after review)     @yprasad1 @narayani28 
- [ ] All unit, extension and client & server smoke tests for the entire product pass – Win , @Nainabhandari8 @jha-g 
- [ ] All unit, extension and client & server smoke tests for the entire product pass – Mac , @Nainabhandari8 @jha-g  
- [ ] All unit, extension and client & server smoke tests for the entire product pass – Linux 32 , @malik-Surbhi @jha-g  
- [ ] All unit, extension and client & server smoke tests for the entire product pass – Linux 64 , @malik-Surbhi @jha-g 
- [ ] Test Win installer / verify digital signature on .msi, .exe, .dlls. Satya Prakash, @Nainabhandari8
- [ ] Test Mac installer / verify digital signature on .app & binaries (both vanilla and bundle)  Satya Prakash, @Nainabhandari8
- [ ] Windows: Scenario testing  @Nainabhandari8
- [ ] Mac: Scenario testing  @Nainabhandari8 
- [ ] Test Linux 32 installer + scenario testing  @malik-Surbhi
- [ ] Test Linux 64 installer + scenario testing  @malik-Surbhi
