### ISSUE TITLE
Release 1.14.1 Deployment Tasks

### ISSUE THREAD

**Issue by yprasad1** [adobe/brackets#14963]
### Tasks to deploy a release publicly
- [ ] Tag the build (brackets, brackets-shell) using `release-1.0` format (Creating 'Release' in brackets tags the build, so only need to do this in brackets-shell?) @jha-g 
- [ ] Announcement to the brackets-dev group for this release and work in the new cycle  @jha-g 
- [ ] Merge localizations/other release changes back into master @jha-g 
- [ ] Merge localizations/other release changes to brackets-shell master @jha-g  
- [ ] Change the health URL to health.brackets.io in the RELEASE branch.  @jha-g 
- [ ] Create a new release on github.com/adobe/brackets/releases @jha-g 
- [ ] Rename and post all 4 platform Builds to github.com/adobe/brackets/releases page @jha-g 
- [ ] Publish the release on github.com/adobe/brackets/releases @jha-g  
- [ ] Update [Health Data Wiki](https://github.com/adobe/brackets/wiki/Health-Data) with the new data that we are sending to the server. @jha-g 
- [ ] Update build number & date in brackets-updates repo _AND_ push Brackets update notifications to brackets.io (_for ALL 5 locales_) @jha-g 
- [ ] Verify posted builds Mac   @malik-Surbhi @jha-g   @Nainabhandari8 
- [ ] Verify posted builds Windows   @malik-Surbhi @jha-g  @Nainabhandari8 
- [ ] Verify posted builds Linux 64   @malik-Surbhi  
- [ ] Verify posted builds Linux 32  @malik-Surbhi  
- [ ] Double-check brackets.io home page to make sure button and new features list look right   @malik-Surbhi 
- [ ] Verify that update notifications work from an older build @Nainabhandari8 
- [ ] Post Blog post --> Vikram
- [ ] Announce release in post to [Facebook](https://www.facebook.com/codebrackets) and [Google+](https://plus.google.com/115365194873502050036/posts), twitter --> Vikram
- [ ] Post announcement in brackets-announce @swmitra, Vikram
- [ ] Gather cycle times from "Ship It!” column
- [ ] Schedule Review Meeting
