### ISSUE TITLE
Release 1.14.2 Tasks

### ISSUE THREAD

**Issue by nayankankariya** [adobe/brackets#15105]
### Tasks in Development
- [x] Review Health Data Stats @niteskum 
- [x] Review Adobe Analytics Data on server.  @niteskum 
- [x] [2 days before] Review bugs open to the current milestone @narayani28 @yprasad1   
- [x] All new open bugs have been reviewed   @narayani28 @yprasad1 
- [x] [2 days before] Notify committers of impending merge of master into release branch @niteskum  
- [x] Notify ALF Team that we have reached String Freeze: `DL-Brackets-IQE`   @narayani28 
- [x] Merge master to the release branch - both _brackets_ & _brackets-shell @niteskum  
- [x] Give a head's up to the Core & LOC teams for release testing  @nayankankariya @niteskum  
- [x] Kick off release build and notify team to start endgame testing when done @niteskum  
- [x] Test the build on a clean VMImage of Win7   @malik-Surbhi 
- [x] Test the build on a clean VMImage of Win8.1   @Nainabhandari8 @malik-Surbhi 
- [x] Test the build on a clean VMImage of Win10   @Abhishek @malik-Surbhi 
- [x] Test the build on a clean Mac machine for 10.15  @Nainabhandari8 
- [x] Test the build on a clean Mac machine for 10.14   @malik-Surbhi 
- [x] Test the build on a clean Mac machine for 10.13   @Ranjitha  
- [ ] ~~Test the build on a clean Ubuntu 64 Bit machine   @Ranjitha~~
- [ ] ~~Test the build on a clean Ubuntu 32 Bit machine   @malik-Surbhi~~ 
- [ ] ~~Test the build on a clean Debian 64 Bit machine   @malik-Surbhi~~ 
- [ ] ~~Test the build on a clean Debian 32 Bit machine   @malik-Surbhi~~ 
- [x] Create a Github Release using release flag for release branch build for all platforms. Delete Obsolete Github Release Builds. @niteskum @swmitra  
- [x] Post to Brackets-Dev Forum: details about [Community Testing](https://github.com/adobe/brackets/wiki/Brackets-Community-Testing)  @swmitra @niteskum  
- [x] Post to Brackets-Dev Forum: request Translations in release branch  @swmitra  @niteskum 
- [x] Create update notifications and send to LOC `DL-Brackets-IQE`. Copy English translations to German & Spanish in case not translated. @niteskum  
- [x] Add new public release info to release update notification  @niteskum  
- [x] Create beginning of next release card. @niteskum  
- [x] Run `grunt set-release --release=N` to update sprint number in master branches(brackets and brackets-shell)  @niteskum 
- [x] New 3rd party code information is added to Third Party Component Usage and NOTICE on github @niteskum  
- [x] Merge update notification translations back from LOC  @niteskum  
- [x] Send reminders to translate Brackets Update Notification strings – Spanish @niteskum  
- [x] Translate Brackets Update Notification strings into German    @malik-Surbhi @niteskum  
- [x] Update Getting Started content and send to loc  @niteskum 
- [x] README and How to Use Brackets" wiki page reviewed and any stale information updated @niteskum 
- [x] Update wiki & TESSA w/ 3rd party dependencies --> @niteskum 
- [x] Write Blog Post --> @narayani28 
- [x] Update [Brackets Loc test procedure](https://github.com/adobe/brackets/wiki/Localization-Tests)  @malik-Surbhi 
- [x] [Release notes](https://github.com/adobe/brackets/wiki/Release-Notes) page on GitHub wiki added with information on features added, bugs fixed in the sprint, and major known issues. All "for release note" bugs added.  @niteskum 
- [x] [Regenerate ](https://github.com/adobe/brackets/wiki/Generating-Brackets-API-Docs)and post API documentation to brackets.io **(Use Mac OS for generating API docs)**  @niteskum  
### Tasks in Testing
- [x] Verify that automated Unit Test Cascade after build succeeded (test jobs succeeded) and then trigger signing process for release candidate.  @niteskum 
- [x] All bugs for all stories completed in the release are closed (or given an exception after review)     @yprasad1 @narayani28 
- [x] All unit, extension and client & server [smoke tests](https://github.com/adobe/brackets/wiki/Brackets-Smoke-Tests) for the entire product pass – Win , @Nainabhandari8  @niteskum 
- [x] All unit, extension and client & server [smoke tests](https://github.com/adobe/brackets/wiki/Brackets-Smoke-Tests) for the entire product pass – Mac , @Ranjitha @niteskum   
- [ ] ~~All unit, extension and client & server [smoke tests](https://github.com/adobe/brackets/wiki/Brackets-Smoke-Tests) for the entire product pass – Linux 32 , @malik-Surbhi @niteskum~~   
- [ ] ~~All unit, extension and client & server [smoke tests](https://github.com/adobe/brackets/wiki/Brackets-Smoke-Tests) for the entire product pass – Linux 64 , @malik-Surbhi @niteskum~~ 
- [x] Test Win installer / verify digital signature on .msi, .exe, .dlls. @satya @Rahul 
- [x] Test Mac Notarization and installer / verify digital signature on .app & binaries (both vanilla and bundle)  @satya @Rahul 
- [x] Windows: Scenario testing  @Ranjitha
- [x] Mac: Scenario testing  @Abhishek 
- [ ] ~~Test Linux 32 installer + scenario testing  @malik-Surbhi~~
- [ ] ~~Test Linux 64 installer + scenario testing  @malik-Surbhi~~

**Comment by nayankankariya** [comment]
Thank you all for closing the tasks.
