### ISSUE TITLE
Release 1.14.2 Deployment Tasks

### ISSUE THREAD

**Issue by nayankankariya** [adobe/brackets#15104]
### Tasks to deploy a release publicly
- [x] Tag the build (brackets, brackets-shell) using `release-1.0` format (Creating 'Release' in brackets tags the build, so only need to do this in brackets-shell?) @niteskum  
- [x] Announcement to the brackets-dev group for this release and work in the new cycle @narayani28 
- [x] Merge localizations/other release changes back into master @niteskum  
- [x] Merge localizations/other release changes to brackets-shell master @niteskum   
- [x] Change the health URL to health.brackets.io in the RELEASE branch.  @niteskum  
- [x] Create a new release on github.com/adobe/brackets/releases @niteskum @swmitra 
- [x] Rename and post all ~~4~~ 2 platform Builds to github.com/adobe/brackets/releases page @niteskum @swmitra 
- [x] Publish the release on github.com/adobe/brackets/releases @niteskum @swmitra 
- [x] Update [Health Data Wiki](https://github.com/adobe/brackets/wiki/Health-Data) with the new data that we are sending to the server. @niteskum 
- [x] Update build number & date in brackets-updates repo _AND_ push Brackets update notifications to brackets.io (_for ALL 5 locales_) @niteskum  @swmitra 
- [x] Verify posted builds Mac   @malik-Surbhi @niteskum @Nainabhandari8 
- [x] Verify posted builds Windows   @malik-Surbhi @niteskum @Nainabhandari8 
- [ ] ~~Verify posted builds Linux 64~~  ~~@malik-Surbhi~~
- [ ] ~~Verify posted builds Linux 32~~ ~~@malik-Surbhi~~
- [x] Double-check brackets.io home page to make sure button and new features list look right   @malik-Surbhi @Nainabhandari8 
- [x] Verify Auto update notification and installation from 1.14.1 to 1.14.2 on Windows @nayankankariya  @malik-Surbhi 
- [x] Verify Auto update notification and installation from 1.14.1 to 1.14.2 on Mac @malik-Surbhi @nayankankariya 
- [x] Post Blog post --> @narayani28  @yprasad1 
- [x] Announce release in post to [Facebook](https://www.facebook.com/codebrackets) and [Google+](https://plus.google.com/115365194873502050036/posts), twitter --> @narayani28 
- [x] Post announcement in brackets-announce --> @Vikram @narayani28 @yprasad1 
- [x] Gather cycle times from "Ship It!” column
- [x] Schedule Review Meeting

**Comment by yprasad1** [comment]
Deployment tasks completed for the release.
