### ISSUE TITLE
Code highlighting issues

### ISSUE THREAD

**Issue by valtlait** [adobe/brackets#6582]
Brackets doesn’t highlight some parts of the code:

![brackets-css-hightlight](https://f.cloud.github.com/assets/5496284/1948096/b3d5234a-807b-11e3-8e3c-4557c244f96f.PNG)

Checked issues has been fixed:
- [x] `from` and `to` keywords inside the `keyframes` scope
- [x] `to`, `top`, `right`, `bottom` and `left` keywords and color values in the `linear-gradient` method [_also other gradient types (repeating… and radial)_]
- [x] values for `-webkit-font-smoothing` (apparently, no support for the property name coming)
- [x] the `-…-user-select` property _[value supported, all unknown properties are now highlighted in the same way as known properties]_ 
- [x] the `animation-fill-mode` property
- [x] tag and attribute selectors inside `:not()`
- [x] the `@supports` rule parameter
- [x] selectors inside the `@supports` scope
- [x] parameter of the `attr()` method

Tested with Brackets 1.4

![brackets-code-highlighting-example](https://cloud.githubusercontent.com/assets/5496284/9529909/954e60d2-4d05-11e5-93cb-d4ad1a2c1d47.png)

**Comment by valtlait** [comment]
All the highlighting issues seems to be fixed, so should we close this issue?
