### ISSUE TITLE
RESEARCH: Measure performance against other editors

### ISSUE THREAD

**Issue by pthiess** [adobe/brackets#9270]
## Areas to measure

* Find in Files
* Switching between / opening files
* Typing (https://github.com/adobe/brackets/issues/11104)
* Scrolling (https://github.com/adobe/brackets/issues/11105)
* Startup time

These can be categorized as mostly rendering (Typing & Scrolling), 
mostly JavaScript (Find in Files), and a mix of the two (Switching between / opening files)

Out of scope:

* Ways to track key performance metrics regularly (per build or per sprint) and graph them -- see [story #357 (Performance Automation)](https://trello.com/c/RWwPlSeO/357-2-performance-automation)
* Ways we could automatically gather performance stats from Brackets in the field as metrics -- fold into Brackets Health Report story

## Which editors should we compare against?
- Sublime
- Atom
- Visual Studio Code
- (Out of scope: Visual Studio, XCode, Notepad++, etc.)

## Measurement approach
- High speed camera: Typing, Scrolling, Switching between files
- Stopwatch: Find in Files (other editors)
- PerfUtils instrumentation: Find in Files (Brackets)

## Project Size
We want to test these features across small, medium and large projects. Large project is defined 30,000+ files. 

What do we consider a small, medium and large Project? Large file? Should we test typing with code hints (and if so which kind), or without?

Do we have example projects that we could leverage for this data collection? Using real world projects would make it definitely more representative.

## Environment
Must use the same machine for all tests to ensure comparable results. Run all tests twice, on:

- Windows 7
- OSX 10.10.3 Retina
- (Out of scope: Windows 8, Mac OSX 10.10 non-Retina, etc.)

## Tasks
- [ ] Define test file(s) for Scrolling/Typing testing
- [ ] Define test project for Find in Files testing
- [ ] Define specific test steps for Typing
- [ ] Define specific test steps for Scrolling
- [ ] Define specific test steps for Switching editors
- [ ] Define specific test steps for Find in Files
- [ ] Decide test hardware for both OSes
- [ ] Install all editors on the test machines
- [ ] Capture high speed camera data (Typing, Scrolling, Switching)
- [ ] Analyze high-speed camera data (Typing, Scrolling, Switching)
- [ ] Find in Files measurements
- [ ] Write up summary report & suggested areas of focus

**Comment by ryanstewart** [comment]
Reopening to target for 1.4. @peterflynn we may have some questions about whether you can help us with the high speed camera.

**Comment by abose** [comment]
Closing as this has been done #11106 #11094 #11105 #11104 #11093
