### ISSUE TITLE
Open File/Folder from Command Line on Mac

### ISSUE THREAD

**Issue by pthiess** [adobe/brackets#9273]
As a user I want to be able to 'cd' to a directory or file from the command line and type 'brackets' to open an instance of brackets with the current folder _or_ file loaded into the file view navigator so I can quickly edit my project files.

* Most of the required work is covered by [Trello card #280] (https://trello.com/c/GhF1Bgf9) (_superseded by https://trello.com/c/U7pQ0yIg/117-5-open-with-brackets-option-from-windows-explorer_), e.g. parsing command line args as things to open, and making sure we reuse an existing instance of Brackets if open
* Add our executable to the PATH at install time.  See RE user story: https://trello.com/c/NRdWorbu/32-br-co-add-to-path
* Make sure command line args are easy to use (don't require passing index.html as first argument)

Successor for [Trello card #349] (https://trello.com/c/dRNqhd2L).

## Tasks
- [ ] Open files passed as command line args
- [ ] Open folders passed as command line args
- [ ] If Brackets already running (& we're not starting a 2nd instance - do we ever?), pass list of files/folders over to the already-running instance
- [ ] Allow passing index.html with a special flag
- [ ] Ensure Windows matches this behavior too
- [ ] Document the hooks that need to get fixed for Linux parity - add notes to [card #1379](https://trello.com/c/6JZLKIHn/1379-open-file-folder-from-command-line-on-linux)

**Comment by nethip** [comment]
This has now landed in master. Closing this. PR at https://github.com/adobe/brackets-shell/pull/513
