### ISSUE TITLE
Health data client initial implementation

### ISSUE THREAD

**Issue by dangoor** [adobe/brackets#9949]
We are ready to implement the [health data](https://github.com/adobe/brackets/wiki/Health-Data) proposal. The goal is to gather information about how Brackets is being used and how well it's working for individuals in order to make Brackets better and to do so in a way that values user privacy.

This issue is tracking the client side implementation of the "Initial Data Proposal".

## Tasks ##

* [ ] Create module with no public API that sends data to a preconfigured location
* [ ] Data is sent daily. If the data cannot be sent on a given day, the record is saved locally and sent on the next attempt
* [x] Generate and save UUID
* [x] Gather data for initial data proposal
    * [x] UUID
    * [x] Snapshot time
    * [x] Brackets version
    * [x] OS
    * [x] OS version
    * [x] OS language
    * [x] Brackets language
    * [x] List of installed extensions *that are available in the registry* and their versions
* [x] Create a dialog (under Help &gt; Health Data?) that says that Adobe collects information to make Brackets better, links to the Health Data wiki page and displays the data that would be sent for the user. There is an opt-out/in checkbox on this dialog.
* [x] On first launch, display a message stating that Adobe will collect data to make Brackets better. Provide a button to open up the Health Data dialog.
* [x] Review of first launch, dialog and wiki page

See also #9950 for the server side implementation
